// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Test_Clock

#ifndef _TEST_CLOCK_UI_H
#define _TEST_CLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_ac_png);    // assets/AC.png
LV_IMG_DECLARE(ui_img_c3_png);    // assets/C3.png
LV_IMG_DECLARE(ui_img_b3_png);    // assets/B3.png
LV_IMG_DECLARE(ui_img_a1_png);    // assets/A1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
